name: CI

on: 
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install requests
    - name: Generate report
      run: bash ./run.sh
    - name: Deploy GitHub pages
      run: |
        export TOKEN=${{ secrets.ACCESS_TOKEN }}
        export DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}
        source ./configs/github.sh
        source ./configs/deploy.sh
